title: tobi exploring, learning and having fun # name of the site
author: Toubi van Kenoubi # name of site's author
email: tobias.schneeberger@gmail.com # email of site's author
url: https://tobisyurt.net # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Tobi having fun in his homelab... Started with a plain old desktop pc repurposed to a NAS with FreeNAS (today TrueNAS Core).
   This got me motivated to do more and more in my homenetwork and today I consider it a hobby.
permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
